Algoritmo "if_else"
//
//
// Descrição   : Aprendendo if e else, o famoso "Se"
// Autor(a)    : Matheus Pinheiro de Oliveira
// Data atual  : 01/07/2025
Var
   // Seção de Declarações das variáveis
   num: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Informe um número ")
   leia (num)

   se num % 2 = 0 entao
      escreval ("O número é PAR!")

   senao
      escreval ("O número é IMPAR!")

   fimse

Fimalgoritmo